from adafruit_bitmap_font import bitmap_font

config = {
    #########################
    # Metro Configuration   #
    #########################
    'station_list': [['C02', '2'], ['C02', '1'], ['E01', '1'], ['E01', '2'], ['A02', '1'], ['A02', '2']],

    #########################
    # Other Values You      #
    # Probably Shouldn't    #
    # Touch                 #
    #########################
    'metro_api_url': 'https://api.wmata.com/StationPrediction.svc/json/GetPrediction/',
    'weather_api_url': 'http://api.openweathermap.org/data/2.5/onecall?',
    'weather_location': 'Washington DC, US',
    'weather_lon': '-77.0364',
    'weather_lat': '38.8951',
    'metro_api_retries': 2,
    'refresh_interval': 5,

    # Display Settings
    'matrix_width': 128,
    'num_trains': 3,
    'font': bitmap_font.load_font('lib/6x10.bdf'),

    'character_width': 5,
    'character_height': 7,
    'text_padding': 1,
    'base_offset': 3,

    'line_header': 'LN',
    'car_header': 'CAR',
    'destination_header': 'DEST',
    'min_header': 'MIN',

    'loading_destination_text': 'Loading',
    'loading_min_text': '---',
    'loading_line_text': '--',

    'train_line_height': 6,
    'train_line_width': 2,

    'car_length_max_characters': 3,
    'min_label_characters': 3,
    'destination_max_characters': 16,

    'red': 0xFF0000,
    'orange': 0xFF5500,
    'yellow': 0xFFFF00,
    'green': 0x00FF00,
    'blue': 0x0000FF,
    'silver': 0xAAAAAA,

    'station_map': {
        'G03': 'Addison Road BL,SV',
        'F06': 'Anacostia GR',
        'F02': 'Archives-Navy GR,YL',
        'C06': 'Arlington Cemetery BL',
        'K04': 'Ballston-MU OR,SV',
        'G01': 'Benning Road BL,SV',
        'A09': 'Bethesda RD',
        'C12': 'Braddock Road BL,YL',
        'F11': 'Branch Ave GR',
        'B05': 'Brookland-CUA RD',
        'G02': 'Capitol Heights BL,SV',
        'D05': 'Capitol South BL,OR,SV',
        'D11': 'Cheverly OR',
        'K02': 'Clarendon OR,SV',
        'A05': 'Cleveland Park RD',
        'E09': 'College Park-U of Md GR',
        'E04': 'Columbia Heights GR,YL',
        'F07': 'Congress Heights GR',
        'K01': 'Court House OR,SV',
        'C09': 'Crystal City BL,YL',
        'D10': 'Deanwood OR',
        'K07': 'Dunn Loring-Merrifield OR',
        'A03': 'Dupont Circle RD',
        'K05': 'East Falls Church OR,SV',
        'D06': 'Eastern Market BL,OR,SV',
        'C14': 'Eisenhower Avenue YL',
        'A02': 'Farragut North RD',
        'C03': 'Farragut West BL,OR,SV',
        'D04': 'Federal Center SW BL,OR,SV',
        'D01': 'Federal Triangle BL,OR,SV',
        'C04': 'Foggy Bottom-GWU BL,OR,SV',
        'B09': 'Forest Glen RD',
        'B06': 'Fort Totten RD',
        'E06': 'Fort Totten GR,YL',
        'J03': 'Franconia-Springfield BL',
        'A08': 'Friendship Heights RD',
        'B01': 'Gallery Pl-Chinatown RD',
        'F01': 'Gallery Pl-Chinatown GR,YL',
        'E05': 'Georgia Ave-Petworth GR,YL',
        'B11': 'Glenmont RD',
        'E10': 'Greenbelt GR',
        'N03': 'Greensboro SV',
        'A11': 'Grosvenor-Strathmore RD',
        'C15': 'Huntington YL',
        'B02': 'Judiciary Square RD',
        'C13': 'King St-Old Town BL,YL',
        'D03': 'LEnfant Plaza BL,OR,SV',
        'F03': 'LEnfant Plaza GR,YL',
        'D12': 'Landover OR',
        'G05': 'Largo Town Center BL,SV',
        'N01': 'McLean SV',
        'C02': 'McPherson Square BL,OR,SV',
        'A10': 'Medical Center RD',
        'A01': 'Metro Center RD',
        'C01': 'Metro Center BL,OR,SV',
        'D09': 'Minnesota Ave OR',
        'G04': 'Morgan Boulevard BL,SV',
        'E01': 'Mt Vernon Sq 7th St GR,YL',
        'F05': 'Navy Yard-Ballpark GR',
        'F09': 'Naylor Road GR',
        'D13': 'New Carrollton OR',
        'B35': 'NoMa-Gallaudet U RD',
        'C07': 'Pentagon BL,YL',
        'C08': 'Pentagon City BL,YL',
        'D07': 'Potomac Ave BL,OR,SV',
        'E08': 'Prince Georges Plaza GR',
        'B04': 'Rhode Island Ave-Brentwood RD',
        'A14': 'Rockville RD',
        'C10': 'National Airport BL,YL',
        'C05': 'Rosslyn BL,OR,SV',
        'A15': 'Shady Grove RD',
        'E02': 'Shaw-Howard U GR,YL',
        'B08': 'Silver Spring RD',
        'D02': 'Smithsonian BL,OR,SV',
        'F08': 'Southern Avenue GR',
        'N04': 'Spring Hill SV',
        'D08': 'Stadium-Armory BL,OR,SV',
        'F10': 'Suitland GR',
        'B07': 'Takoma RD',
        'A07': 'Tenleytown-AU RD',
        'A13': 'Twinbrook RD',
        'N02': 'Tysons Corner SV',
        'E03': 'U Street GR,YL',
        'B03': 'Union Station RD',
        'J02': 'Van Dorn Street BL',
        'A06': 'Van Ness-UDC RD',
        'K08': 'Vienna/Fairfax-GMU OR',
        'K03': 'Virginia Square-GMU OR,SV',
        'F04': 'Waterfront GR',
        'K06': 'West Falls Church OR',
        'E07': 'West Hyattsville GR',
        'B10': 'Wheaton RD',
        'A12': 'White Flint RD',
        'N06': 'Wiehle-Reston East SV',
        'A04': 'Woodley Park-Zoo RD'
    }
}
