from adafruit_bitmap_font import bitmap_font

config = {

    'auto_restart': True,
    'log_level': 'INFO',

    #########################
    # Metro Configuration   #
    #########################
    'station_list': [['C02', '2'], ['C02', '1'], ['E01', '1'], ['E01', '2'], ['A02', '1'], ['A02', '2']],

    #########################
    # Other Values You      #
    # Probably Shouldn't    #
    # Touch                 #
    #########################
    'metro_api_url': 'https://api.wmata.com/StationPrediction.svc/json/GetPrediction/',
    'weather_api_url': 'http://api.openweathermap.org/data/2.5/onecall?',
    'weather_location': 'Washington DC, US',
    'weather_lon': '-77.03214',
    'weather_lat': '38.90688',

    # Display Settings
    'matrix_width': 128,
    'num_trains': 3,
    'font': bitmap_font.load_font('lib/6x10.bdf'),

    'character_width': 6,
    'character_height': 7,
    'text_padding': 1,
    'base_offset': 3,

    'red': 0xFF0000,
    'orange': 0xFF5500,
    'yellow': 0xFFFF00,
    'green': 0x00FF00,
    'blue': 0x0000FF,
    'silver': 0xAAAAAA,
    'off': 0x000000,

    'station_map': {
        'G03': 'Addison Road \nBL,SV',
        'F06': 'Anacostia \nGR',
        'F02': 'Archives-Navy \nGR,YL',
        'C06': 'Arlington Cemetery \nBL',
        'K04': 'Ballston-MU \nOR,SV',
        'G01': 'Benning Road \nBL,SV',
        'A09': 'Bethesda \nRD',
        'C12': 'Braddock Road \nBL,YL',
        'F11': 'Branch Ave \nGR',
        'B05': 'Brookland-CUA \nRD',
        'G02': 'Capitol Heights \nBL,SV',
        'D05': 'Capitol South \nBL,OR,SV',
        'D11': 'Cheverly \nOR',
        'K02': 'Clarendon \nOR,SV',
        'A05': 'Cleveland Park \nRD',
        'E09': 'College Park-U of \nMd GR',
        'E04': 'Columbia Heights \nGR,YL',
        'F07': 'Congress Heights \nGR',
        'K01': 'Court House \nOR,SV',
        'C09': 'Crystal City \nBL,YL',
        'D10': 'Deanwood \nOR',
        'K07': 'Dunn Loring-Merrifield \nOR',
        'A03': 'Dupont Circle \nRD',
        'K05': 'East Falls Church \nOR,SV',
        'D06': 'Eastern Market \nBL,OR,SV',
        'C14': 'Eisenhower Avenue \nYL',
        'A02': 'Farragut North \nRD',
        'C03': 'Farragut West \nBL,OR,SV',
        'D04': 'Federal Center SW \nBL,OR,SV',
        'D01': 'Federal Triangle \nBL,OR,SV',
        'C04': 'Foggy Bottom-GWU \nBL,OR,SV',
        'B09': 'Forest Glen \nRD',
        'B06': 'Fort Totten \nRD',
        'E06': 'Fort Totten \nGR,YL',
        'J03': 'Franconia-Springfield \nBL',
        'A08': 'Friendship Heights \nRD',
        'B01': 'Gallery Pl-Chinatown \nRD',
        'F01': 'Gallery Pl-Chinatown \nGR,YL',
        'E05': 'Georgia Ave-Petworth \nGR,YL',
        'B11': 'Glenmont \nRD',
        'E10': 'Greenbelt \nGR',
        'N03': 'Greensboro \nSV',
        'A11': 'Grosvenor-Strathmore \nRD',
        'C15': 'Huntington \nYL',
        'B02': 'Judiciary Square \nRD',
        'C13': 'King St-Old Town \nBL,YL',
        'D03': 'LEnfant Plaza \nBL,OR,SV',
        'F03': 'LEnfant Plaza \nGR,YL',
        'D12': 'Landover \nOR',
        'G05': 'Largo Town Center \nBL,SV',
        'N01': 'McLean \nSV',
        'C02': 'McPherson Square \nBL,OR,SV',
        'A10': 'Medical Center \nRD',
        'A01': 'Metro Center \nRD',
        'C01': 'Metro Center \nBL,OR,SV',
        'D09': 'Minnesota Ave \nOR',
        'G04': 'Morgan Boulevard \nBL,SV',
        'E01': 'Mt Vernon Sq 7th St \nGR,YL',
        'F05': 'Navy Yard-Ballpark \nGR',
        'F09': 'Naylor Road \nGR',
        'D13': 'New Carrollton \nOR',
        'B35': 'NoMa-Gallaudet U \nRD',
        'C07': 'Pentagon \nBL,YL',
        'C08': 'Pentagon City \nBL,YL',
        'D07': 'Potomac Ave \nBL,OR,SV',
        'E08': 'Prince Georges Plaza \nGR',
        'B04': 'Rhode Island Ave-Brentwood \nRD',
        'A14': 'Rockville \nRD',
        'C10': 'National Airport \nBL,YL',
        'C05': 'Rosslyn \nBL,OR,SV',
        'A15': 'Shady Grove \nRD',
        'E02': 'Shaw-Howard U \nGR,YL',
        'B08': 'Silver Spring \nRD',
        'D02': 'Smithsonian \nBL,OR,SV',
        'F08': 'Southern Avenue \nGR',
        'N04': 'Spring Hill \nSV',
        'D08': 'Stadium-Armory \nBL,OR,SV',
        'F10': 'Suitland \nGR',
        'B07': 'Takoma \nRD',
        'A07': 'Tenleytown-AU \nRD',
        'A13': 'Twinbrook \nRD',
        'N02': 'Tysons Corner \nSV',
        'E03': 'U Street \nGR,YL',
        'B03': 'Union Station \nRD',
        'J02': 'Van Dorn Street \nBL',
        'A06': 'Van Ness-UDC \nRD',
        'K08': 'Vienna/Fairfax-GMU \nOR',
        'K03': 'Virginia Square-GMU \nOR,SV',
        'F04': 'Waterfront \nGR',
        'K06': 'West Falls Church \nOR',
        'E07': 'West Hyattsville \nGR',
        'B10': 'Wheaton \nRD',
        'A12': 'White Flint \nRD',
        'N06': 'Wiehle-Reston East \nSV',
        'A04': 'Woodley Park-Zoo \nRD'
    }
}
